### ISSUE TITLE
problem with install

### ISSUE THREAD

**Issue by drtinaz** [arrow1800/Victron-VirtualBattery#8] opened 2023-03-21 17:05 UTC
I have followed all the instruction, but when I get to the last step I get the following result

./data/dbus-virtual-battery/install.sh: line 8: syntax error near unexpect
ed token `newline'
./data/dbus-virtual-battery/install.sh: line 8: `<!DOCTYPE html>'

**Comment by arrow1800** [comment] 2023-03-21 17:29
hi @thomasinaz41213 i think this was/is caused by the wrong line endings in those files. i changed it. could you try again?

**Comment by drtinaz** [comment] 2023-03-21 18:03
I have deleted and re uploaded the files but still get the same result when i run the install script

**Comment by drtinaz** [comment] 2023-03-21 20:29
I finally got it figured out. Being brand new to all this linux stuff I was not transfering the files correctly from the github. It is working now. Thank you so much.

On another note, would it be possible to add the option for a stepped maximum charging voltage based on soc?

**Comment by drtinaz** [comment] 2023-03-21 22:27
> hi @thomasinaz41213 i think this was/is caused by the wrong line endings in those files. i changed it. could you try again?

I got everything working but now I can't uninstall it. The uninstall script seems to have a problem.


root@einstein:/# ./data/dbus-virtual-battery/uninstall.sh
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or
 kill -l [sigspec]
./data/dbus-virtual-battery/uninstall.sh: line 8: ./restart.sh: No such fi
le or directory

I tried to run the uninstall script from the root directory as well as from dbus-virtual-battery directory with the same results

**Comment by arrow1800** [comment] 2023-03-22 10:07
> I finally got it figured out. Being brand new to all this linux stuff I was not transfering the files correctly from the github. It is working now. Thank you so much.
> 
> On another note, would it be possible to add the option for a stepped maximum charging voltage based on soc?

yes offcourse. you can build this yourself in node-red. an example (still tuning it myself as well):

![image](https://user-images.githubusercontent.com/12893401/226869849-81641737-b442-4ba6-af3a-3dee1fb9b02b.png)

**Comment by arrow1800** [comment] 2023-03-22 10:50
> > hi @thomasinaz41213 i think this was/is caused by the wrong line endings in those files. i changed it. could you try again?
> 
> I got everything working but now I can't uninstall it. The uninstall script seems to have a problem.
> 
> root@einstein:/# ./data/dbus-virtual-battery/uninstall.sh kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec] ./data/dbus-virtual-battery/uninstall.sh: line 8: ./restart.sh: No such fi le or directory
> 
> I tried to run the uninstall script from the root directory as well as from dbus-virtual-battery directory with the same results

committed a minor fix for the uninstall.sh script. you can try again. 

running these scripts (install,restart,uninstall) is the easiest from the root folder -> `root@einstein:/#` 

run them by typing this: `./data/dbus-virtualbattery/filename.sh`

please let me know if it works

**Comment by morres83** [comment] 2023-03-22 16:33
I also encountered a problem, the scripts are somehow dependent on the folder name and file names. In other scripts it was the same (folder name= file name).

For my MQTT version I will do the same (folder name= file name), then I am consistent throughout my other scripts.

**Comment by arrow1800** [comment] 2023-03-23 11:03
> I also encountered a problem, the scripts are somehow dependent on the folder name and file names. In other scripts it was the same (folder name= file name).
> 
> For my MQTT version I will do the same (folder name= file name), then I am consistent throughout my other scripts.

is there still a problem that needs to be fixed or is this more like an enhancement?

**Comment by morres83** [comment] 2023-03-23 15:54
Please check with ps on your system how the processes are called.
It seems that `SERVICE_NAME` is equal to the folder name, so this line in uninstall.sh might fail.

`kill $(pgrep -f 'supervise virtualbattery')`

So either call the folder also virtualbattery (and update README), or update the uninstall.sh file so such it contains the folder name.

**Comment by arrow1800** [comment] 2023-03-23 16:19
modified. closing this issue for now, if anything new arises, feel free to make a new issue

**Closed as completed by arrow1800** 2023-03-23 16:19 UTC
